old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     5672
            user:     '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        authentification_check:
            connection:       default
            exchange_options: {name: 'authentification-check', type: direct}
        tasks_retrieve:
            connection:       default
            exchange_options: {name: 'tasks-retrieve', type: direct}
        queue_run:
            connection:       default
            exchange_options: {name: 'queue-run', type: direct}
    consumers:
        authentification_check:
            connection:       default
            exchange_options: {name: 'authentification-check', type: direct}
            queue_options:    {name: 'authentification-check'}
            callback:         app.authentification_check_consumer
        tasks_retrieve:
            connection:       default
            exchange_options: {name: 'tasks-retrieve', type: direct}
            queue_options:    {name: 'tasks-retrieve'}
            callback:         app.tasks_retrieve_consumer
        queue_run:
            connection:       default
            exchange_options: {name: 'queue-run', type: direct}
            queue_options:    {name: 'queue-run'}
            callback:         app.queue_run_consumer
