app:
    resource: "@AppBundle/Controller"
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    options: { i18n: false }

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options: { i18n: false }

LexikMailerBundle:
    resource: "@LexikMailerBundle/Resources/config/routing.xml"
    prefix:   /admin/
    options: { i18n: false }

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /admin/i18n
    options: { i18n: false }

sylius_cart_summary:
    path: /cart
    defaults: { _controller: sylius.controller.cart:summaryAction }

app_cart_add:
    pattern: /cart/add/{slug}
    defaults: { _controller: AppBundle:Cart:add }

sylius_cart_clear:
    path: /cart/clear
    defaults: { _controller: sylius.controller.cart:clearAction }

#FosUserBundle Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account

fos_user_reset_password:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /account

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account

fos_user_profile_show:
    pattern: /account/edit
    defaults: { _controller: AppBundle:Home:home }

fos_user_profile_edit:
    pattern: /account/edit
    defaults: { _controller: AppBundle:Home:home }

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

github_login:
    pattern: /login/check-github

bitbucket_login:
    pattern: /login/check-bitbucket
